# Generated by Django 5.0.1 on 2024-01-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('WAITING', 'WAITING'), ('ATTEND', 'ATTEND'), ('CANCELED', 'CANCELED'), ('ATTENDED', 'ATTENDED')], default='WAITING', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'waiting_turn',
            },
        ),
    ]
